#DataSource Configuration
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-rest?useUnicode=true&characterEncoding=utf8
    username: root
    password: noobLESS12345
  jackson:
    date-format: yyyy-MM-dd
server:
  servlet:
    contextPath: /api
springdoc:
  api-docs.enabled: true
  api-docs.path: /javainuse-openapi
  swagger-ui.path: /swagger-ui